# Use an official Node.js image as the base image
FROM node:20.0.0-alpine AS backend

# Set the working directory for backend
WORKDIR /app/quirknotes/backend

# Copy backend package files
COPY quirknotes/backend/package*.json ./

#Install dependencies
RUN npm install

# Copy backend source code
COPY quirknotes/backend ./

# Expose port 4000 for the backend server
EXPOSE 4000

# Command to start the backend server
CMD ["npm", "start"]
